M48
; DRILL file {KiCad 8.0.3-8.0.3-0~ubuntu20.04.1} date 2025-03-17T01:47:46-0300
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-03-17T01:47:46-03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.3-8.0.3-0~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
%
G90
G05
T1
X56.605Y-63.61
X56.605Y-69.39
M30
